name: API Automation Tests


on:
  push:
    branches:
      - rishika-final-capstone

  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v4



      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven



      - name: Verify Docker
        run: docker --version


      - name: Run Tests
        working-directory: api-Automation
        run: mvn test